spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/saas?serverTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver
#    schema:
#      - classpath:department.sql
#    type: com.alibaba.druid.pool.DruidDataSource

































































































